id: P008167
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG10387
  title: རྒྱ་གཞུང་གྲགས་ཆེ་བ་འགའ་ཞིག་གི་ཁ་བྱང་།
  author: ''
  volumes:
    b9ea1928068d41528dec588d881862ad:
      image_group_id: I1KG10429
      title: ''
      volume_number: 1
      total_pages: 30
      base_file: v001.txt
